In [1]:
import pandas as pd

In [10]:
data = {
    'pH': [6.5, 8.5, 6.6, 6.6, 6.5, 6.6, 6.5, 6.8, 6.6, 6.7],
    'Temprature': [36, 70, 43, 50, 38, 45, 37, 45, 45, 45],
    'Taste': [0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
    'Odor': [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'Turbidity': [0, 0, 1, 1, 0, 1, 0, 1, 1, 0],
    'Colour': [247, 246, 250, 250, 255, 250, 255, 255, 250, 245],
    'Grade': ['medium', 'low', 'high', 'low', 'medium', 'medium', 'medium',
       'high', 'medium', 'medium']
    
}

In [11]:
df = pd.DataFrame(data)

MAPPING LOW MEDIUM AND HIGH AS 0 1 2 RESPECTIVELY

In [12]:
df

    pH  Temprature  Taste  Odor  Turbidity  Colour   Grade
0  6.5          36      0     0          0     247  medium
1  8.5          70      0     0          0     246     low
2  6.6          43      1     0          1     250    high
3  6.6          50      0     0          1     250     low
4  6.5          38      1     0          0     255  medium
5  6.6          45      0     0          1     250  medium
6  6.5          37      0     0          0     255  medium
7  6.8          45      0     1          1     255    high
8  6.6          45      0     0          1     250  medium
9  6.7          45      1     1          0     245  medium

In [13]:
df['Grade']=df['Grade'].map({'low':0,'medium':1,'high':3})

In [14]:
df

    pH  Temprature  Taste  Odor  Turbidity  Colour  Grade
0  6.5          36      0     0          0     247      1
1  8.5          70      0     0          0     246      0
2  6.6          43      1     0          1     250      3
3  6.6          50      0     0          1     250      0
4  6.5          38      1     0          0     255      1
5  6.6          45      0     0          1     250      1
6  6.5          37      0     0          0     255      1
7  6.8          45      0     1          1     255      3
8  6.6          45      0     0          1     250      1
9  6.7          45      1     1          0     245      1

In [16]:
X = df.drop(['Grade'],axis=1)
y = df['Grade']

In [20]:
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
svm = SVC(gamma = 'auto')
gnb = GaussianNB()

In [21]:
n = int(input('Enter an option\n 0. Exit\n 1. SVM\n 2. Naive Bayes\n '))


class Classifier():
    def svm():
        svm.fit(X, y)
        print('The accuracy of SVM is ',svm.score(X, y))
        print('The predicted values are ', list(svm.predict(X)))
        print('\n')

    def gnb():
        gnb.fit(X, y)
        print('The accuracy of Gaussian Naive Bayes is ',gnb.score(X, y))
        print('The predicted values are ', list(gnb.predict(X)))
        print('\n')



while True:
    if n == 0:
        break
    elif n == 1:
        Classifier.svm()
    elif n == 2:
        Classifier.gnb()
    n = int(input('Enter an option\n 0. Exit\n 1. SVM\n 2. Naive Bayes\n '))

The accuracy of SVM is  1.0
The predicted values are  [1, 0, 3, 0, 1, 1, 1, 3, 1, 1]


The accuracy of Gaussian Naive Bayes is  0.6
The predicted values are  [0, 0, 3, 0, 1, 0, 0, 3, 0, 1]